#!/bin/bash
# Spectrograph  Copyright (C) 2015  Lukáš Ondráček <ondracek.lukas@gmail.com>, see README file

i=0
fifo=`mktemp -u`
while ! mkfifo "$fifo"; do
	trap "rm -f '$fifo'" EXIT
	fifo=`mktemp -u`
	if ((i++>5)); then
		echo "Cannot create named pipe." >&2
		exit 1
	fi
done

tee "$fifo" | `dirname $0`/play-raw "$@" &
cat "$fifo"
